// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"strike_layout_template/internal/biz"
	"strike_layout_template/internal/conf"
	"strike_layout_template/internal/data"
	"strike_layout_template/internal/server"
	"strike_layout_template/internal/service"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data) (*server.Server, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService)
	engine := server.NewHTTPServer(confServer, greeterService)
	serverServer := newApp(grpcServer, engine)
	return serverServer, func() {
		cleanup()
	}, nil
}
